[build]
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200